### ISSUE TITLE
__FILE__ returns `init.el` path when installing during loading of Emacs

### ISSUE THREAD

**Issue by syl20bnr** [rocky/emacs-load-relative#6]
For more info see: https://github.com/syl20bnr/spacemacs/issues/5917#issuecomment-215433961

**Comment by syl20bnr** [comment]
Reproduce the comment linked above here for convenience:

More info.

The error seems to come from `__FILE__` function in `load-relative.el`.

_With paradox:_

```
load-file-name: /Users/sylvain/.emacs.d/elpa/load-relative-20150224.1722/load-relative.elc
looking for: ./realgud/common/track-mode
with prefix: realgud-
;; in __FILE__
__FILE__ result is: nil
```

_With Spacemacs:_

```
load-file-name: /Users/sylvain/.emacs.d/elpa/load-relative-20150224.1722/load-relative.elc
looking for: ./realgud/common/track-mode
with prefix: realgud-
;; in __FILE__
load-file-name: /Users/sylvain/.emacs.d/init.el
__FILE__ result is: /Users/sylvain/.emacs.d/init.el
```

So it seems that anyone installing their packages from their emacs loading process in `init.el` would hit the bug.

**Comment by tom-seddon** [comment]
I'm still hitting this problem (I think) when trying to install realgud from my init file.

I've got the following as `/home/tom/.emacs.d/lisp/configure/configure-realgud.el`, which is required from my startup file, which is required from my `~/.emacs.d/init.el`.

```
;; https://github.com/realgud/realgud/wiki/How-to-Install

(unless (package-installed-p 'realgud)
  (package-install 'realgud))

(provide 'configure-realgud)
```

When I start Emacs, it looks like it's doing the realgud installation, but then the *Compile-Log* buffer pops up with a zillion errors along the following lines. It appears to be looking for everything in my `.emacs.d/lisp/configure` folder:

`realgud.el:81:1:Error: Cannot open load file: no such file or directory, /home/tom/.emacs.d/lisp/configure/realgud/common/track-mode`

Interactive installation does work.

I'm not using spacemacs.

--Tom

P.S. emacs 24.5.1 (from the Ubuntu package manager)

**Comment by tom-seddon** [comment]
Fared better on Emacs 25.1.50.1 (on my other Linux PC) - installed OK, and I could start gdb and step through a couple of lines of code. Only a brief test, though... literally pressed F10 a couple of times... but it seems to work.

I do get some errors at the end of the `*Compile-Log*` buffer, though... don't know if those are to be expected. Full log here: https://gist.github.com/tom-seddon/8f7ee0878d494a8df4d692c0e26c835f

Thanks,

--Tom
